# Perform a dry-run no pull-requests
name: "PR Review Queue Dry Run"

on:
  pull_request

jobs:
  weekly:
    name: Daily PR review queue dry run
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ochosi/pr-review-queue:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Create PR Review Queue for osbuild/osbuild
        run: |
          python3 pr_review_queue.py --github-token "${{ secrets.GITHUB_TOKEN }}" --queue --org osbuild --repo osbuild --dry-run
        shell: bash